[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://eiwaahome.netlify.app"
  NODE_VERSION = "18"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dzwkeydij"
  NEXTAUTH_URL = "https://eiwaahome.netlify.app"
  NEXTAUTH_SECRET = "eiwaahomeauthsecretkey2024"
  DATABASE_URL = "mongodb+srv://finaleewa:finaleewa@finaleewa.7eytc2o.mongodb.net/finaleewa?retryWrites=true&w=majority&appName=finaleewa"
  NODE_ENV = "production"
  PRISMA_SCHEMA_PATH = "prisma/schema.prisma"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  included_files = ["node_modules/.prisma/**/*.node", "prisma/schema.prisma", "schema.prisma", "prisma/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"] 