[build]
  command = "npm run netlify-build"
  publish = ".next"
  functions = "netlify/functions"
  [build.lifecycle]
    onBuild = "node netlify-prebuild.js"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  PRISMA_SCHEMA_PATH = "./prisma/schema.prisma"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Pre-build script to prepare environment and database
[[plugins]]
  package = "netlify-plugin-inline-functions-env"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs"
  status = 200
  force = true

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize for performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https:; media-src 'self' https:; object-src 'none'; frame-src 'self' https:;" 