# Build settings
[build]
  command = "npm run netlify:build"
  publish = ".next"
  functions = "netlify/functions"

# Environment variables
[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  PRISMA_SCHEMA_PATH = "./prisma/schema.prisma"

# Optimize processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true

# Function settings
[functions]
  included_files = ["**/*.js", "**/*.ts", "**/*.json", "**/*.prisma", "prisma/schema.prisma"]
  node_bundler = "esbuild"

# API endpoint redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-bridge/:splat"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

# Cache control for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:; frame-src https:; object-src 'none'"

# Add Next.js-specific handling
[[plugins]]
  package = "@netlify/plugin-nextjs" 